<?php

namespace AppBundle\Repository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
    public function get_all_tweets()
    {
        return $this->findAll();
    }
}
