<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tweet;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $maxresults
     * @return array
     */
    public function getLastTweets($maxresults)
    {
        return $this->createQueryBuilder('t')
            ->select('t.message,t.id,t.createdAt')
            ->orderBy('t.createdAt','DESC')
            ->setMaxResults($maxresults)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $idTweet
     * @return mixed
     */
    public function getTweetById($idTweet)
    {
        return $this->createQueryBuilder('t')
            ->select('t.message,t.id,t.createdAt')
            ->where('t.id = :id')
            ->setParameter(':id',$idTweet)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
